pipeline{
    agent any
    stages{
        stage('Pull_From_Github'){
            steps{
                echo 'Pulling from github'
                git branch: 'main',
                    url: 'https://github.com/princedan-123/alx-backend-python.git',
                    credentialsId: 'git_token'
                
            }
        }
        stage('Install dependencies') {
            steps {
                dir('messaging_app'){
                    sh 'pip3 install -r messaging_app/requirements.txt'
                }
            }
        }
        stage('Build docker image for messaging app') {
            step {
                sh 'touch Dockerfile'
                sh 'echo "FROM python:3.11-alpine" >> Dockerfile'
                sh 'echo "RUN pip install -r requirements.txt" >> Dockerfile'
                sh sudo docker build -t messaging_app:lastest .
            }
        }
    }
}
