version: "3.9"

services:
  web:
    build: .
    container_name: my_web_app
    ports:
      - "8000:8000" 
    volumes:
      - .:/app # Bind Mount
    depends_on: 
      - db
    networks:
      - app_network

  db:
    image: mysql:8.0
    container_name: my_database
    environment:
      - MYSQL_USER=${mysql_user}
      - MYSQL_DB=${mysql_db}
      - MYSQL_PASSWORD=${mysql_password}
    volumes:
      - db_data:/var/lib/postgresql/data  # Named volume
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
